name: Substreams
on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Substreams CLI
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: streamingfast/substreams
          tag: v0.2.0
          platform: linux
          arch: x86-64

      - name: Compile WASM
        run: make

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.spkg